### PR TITLE
FrontEnd: Re-factor the overall layout #40

### PR DESCRIPTION
**Pull request by kam56**
# Implement the overall layout according to the prototype

## Description
* Create a `SideBar `component for the buttons to increase the `App.svelte` file readability 
* Create a `Button` component to reduce code repetition 
* Modify the `App.svelte` file to use the components 
* Modify the panels' styles to match the overall prototype 
* Modify the `FilterWidget` component display option 
* Modify the `Timebar` icon path to match the Button component structure. 
* Update the background colors to match the prototype
* Update the `Timebar` panel background color to match the layout

### Overall app

Screenshot 2022-11-23 at 16 43 38

### When the panels are toggled on
Screenshot 2022-11-23 at 16 43 22

## Testing 
* Tested locally with both the database dump data and the original event generator. 
* The performance was not impacted 

## Possible Improvements
* The `ColorLegend` background is too similar to the main background and its width is smaller than the filter panel. There is another PR regarding updating the legend. https://github.com/ItJustWorksTM/EiffelVis/pull/124 
* There is a gap between the color legend and the filter panel, but that is solved in [US15](https://github.com/ItJustWorksBetterTM/EiffelVis/pull/42). 

closes #40

### CODE REVIEW

**Comment by alrapal** [comment]
Nice! I will review this during the day! I see there are conflicts that come most likely from the fact that develop is not synced with master. I will first look at that =D

**Comment by kam56** [comment]
> Nice! I will review this during the day! I see there are conflicts that come most likely from the fact that develop is not synced with master. I will first look at that =D

Thank you. Yes, I saw the conflicts but I wasn't sure what to do. Since the new legend, the updated filter panel and new SVGs are merged into dev. Should we discard them?

**Comment by kam56** [comment]
Close the PR, since we will create another one to a new develop branch

**Comment by alrapal** [comment]
New PR #49

**Pull request closed without merging**
