### PR TITLE
Noip rpi environment

### PR DESCRIPTION
**Pull request by ktpa**
The previous error reported is present in master branch as well and will require another PR to be solved. This is safe to merge into develop from that perspective. 

Changed address to better reflect product name:
- http://eiffelvis.ddns.net:8080
- http://eiffelvis.ddns.net:5672
- http://eiffelvis.ddns.net:3001

### CODE REVIEW

**Review by alrapal — COMMENTED** [review]
I guess the previous error is the one in #25 ? 
I tried to reproduce it with the upstream main, but I cannot get the event generator to run. So I will write a ticket on the upstream repo to get info or report a bug. 

Regarding this PR, if I understand correctly, this allows to use the given hosts as URL access (in development mode and if we give the right port of course). 

I assume this piece of code should not be pushed to the upstream repo, since it is for our test purpose? 
How do we protect our test env if the host name is visible on GitHub, and what happens if other team members are running this locally, wouldn't it conflict with the test env? Should we only use localhost? 

(Very naïve questions, you know I am not a network engineer haha)!

**Comment by ktpa** [comment]
We can hide it with an .env if we want to, sure. 

You can always define channel "hello" on upstream/master and the event gen should work fine.

**Comment by alrapal** [comment]
> We can hide it with an .env if we want to, sure.
> 
> You can always define channel "hello" on upstream/master and the event gen should work fine.

I think that would be safer and neater yes! Let's not expose ourselves too much 😄 

Ok, it might just be me doing something wrong, because I tried and gave the channel name using -r "hello" on both side, but I must have used the wrong parameter! I will have a look at that, or you can show me directly when you have a moment! 

If it is a bug from the upstream repo, then we will do an issue and maybe take care of it in that case.

**Review by alrapal — CHANGES_REQUESTED** [review]
Would be better Include those elements in an env file to avoid exposing our test server as you suggested

**Review by alrapal — COMMENTED** [review]
Ok! So now there is no .env file in the repo, just the .env.example? 
It is a nice idea to have the env.example file! 
One problem I see with the current state, is that since we don't have a .env file anymore, the frontend will not be able to connect to the backend since it will not have the port stated. 
Maybe the easiest is to have a placeholder in the real .env, but change it on every machine we use to develop to avoid having it exposed?

we could add this `EIFFELVIS_TEST_URL = "mytesturl.com"` in the real .env but change it on the team level?

Also, if this is going to be merged to the upstream main, we might want to change the readme to specify the use of this file, for better clarity (like a warning to change the test server URL for something custom to avoid having it exposed) 

What do you think? (We have time anyway, we need to fix the CI :p)

**Comment by ktpa** [comment]
> Ok! So now there is no .env file in the repo, just the .env.example? It is a nice idea to have the env.example file! One problem I see with the current state, is that since we don't have a .env file anymore, the frontend will not be able to connect to the backend since it will not have the port stated. Maybe the easiest is to have a placeholder in the real .env, but change it on every machine we use to develop to avoid having it exposed?
> 
> we could add this `EIFFELVIS_TEST_URL = "mytesturl.com"` in the real .env but change it on the team level?
> 
> Also, if this is going to be merged to the upstream main, we might want to change the readme to specify the use of this file, for better clarity (like a warning to change the test server URL for something custom to avoid having it exposed)
> 
> What do you think? (We have time anyway, we need to fix the CI :p)

The whole idea with an .env file is to have hidden addresses and/or usernames, database names, logins, you name it without sharing it. That's why I removed it from git, because having an .env file on the repository is contradictory to its purpose. 

So everyone that wants to run the software has to create their own .env or ask for the right credentials through malicious (social) software engineering and maybe we can leak it. But this is the way it is _supposed_ to be done.

**Comment by alrapal** [comment]
> > Ok! So now there is no .env file in the repo, just the .env.example? It is a nice idea to have the env.example file! One problem I see with the current state, is that since we don't have a .env file anymore, the frontend will not be able to connect to the backend since it will not have the port stated. Maybe the easiest is to have a placeholder in the real .env, but change it on every machine we use to develop to avoid having it exposed?
> > we could add this `EIFFELVIS_TEST_URL = "mytesturl.com"` in the real .env but change it on the team level?
> > Also, if this is going to be merged to the upstream main, we might want to change the readme to specify the use of this file, for better clarity (like a warning to change the test server URL for something custom to avoid having it exposed)
> > What do you think? (We have time anyway, we need to fix the CI :p)
> 
> The whole idea with an .env file is to have hidden addresses and/or usernames, database names, logins, you name it without sharing it. That's why I removed it from git, because having an .env file on the repository is contradictory to its purpose.
> 
> So everyone that wants to run the software has to create their own .env or ask for the right credentials through malicious (social) software engineering and maybe we can leak it. But this is the way it is _supposed_ to be done.

Yes, I agree, it is how it is supposed to be used :), was just thinking about how the overall thing works atm. But you are right.  
We just have to specify that in the readme for developers because atm it is not stated. Do you think this could be included in this PR or do we create a new task to update the readme (I think other things need to be stated in there, about the generator for instance, it kind of lack guidance). 

The backend connects and expects port 3001 though, so maybe the port 3001 can stay in the .env.example file?

**Comment by ktpa** [comment]
> Yes, I agree, it is how it is supposed to be used :), was just thinking about how the overall thing works atm. But you are right. We just have to specify that in the readme for developers because atm it is not stated. Do you think this could be included in this PR or do we create a new task to update the readme (I think other things need to be stated in there, about the generator for instance, it kind of lack guidance).
> 
> The backend connects and expects port 3001 though, so maybe the port 3001 can stay in the .env.example file?

Sorry, I must have misread your message. We can definitely define it here, as it is detrimental to this PRs functionality. The port itself isn't that much of a secret, no so you're correct.

**Review by alrapal — APPROVED** [review]
Nice! Well done!

**Comment by ktpa** [comment]
Closing this to test the branch rules once again.

**Pull request merged**
