### PR TITLE
Frontend: Refactor the overall layout

### LINKED ISSUE #34: Rework of app design
## Description
App should be reworked following this [prototype](https://www.figma.com/proto/nUvQFcBLjBwBXy55isFmrn/Eiffelvis_prototype_web?page-id=65%3A134&node-id=157%3A114&starting-point-node-id=157%3A114&show-proto-sidebar=1)

## Acceptance criteria
- [ ] Code is commented
- [ ] Code uses typescript
- [ ] Result presents the prototyped design
- [ ] Legend can be a placeholder
- [ ] Page should stay responsive (For bigger screen mostly)

### PR DESCRIPTION
**Pull request by kam56**
Original PR:  https://github.com/ItJustWorksBetterTM/EiffelVis/pull/49

# Implement the overall layout according to the prototype

## Description
* Create a `SideBar` component for the buttons to increase the `App.svelte` file readability 
* Create a `Button` component to reduce code repetition 
* Modify the `App.svelte` file to use the components 
* Modify the panels' styles to match the overall prototype 
* Modify the `FilterWidget` component display option 
* Modify the `Timebar` icon path to match the Button component structure. 
* Update the background colors to match the prototype
* Update the `Timebar` panel background color to match the layout
* Add data types to the ones missing at declaration time. To increase the code quality and follow the correct typescript syntax, this point is applied to all the files. 
* Remove the scroll bar which was only visible on high resolution screens. 

### Overall app

Screenshot 2022-12-01 at 16 41 36

#### When the 'Graph options' is toggled on, the 'legend' is hidden and vice versa. 

Screenshot 2022-12-01 at 16 42 00

Screenshot 2022-12-01 at 16 41 49

## Testing 
* Tested locally with both the database dump data and the original event generator. 
* The performance was not impacted 
* Two of the team members have reviewed the performance locally.

## Possible Improvements

* There is a gap between the color legend/graph options and the filter panel, but we have a plan for it. 

closes #40
closes #34

### CODE REVIEW

**Comment by ktpa** [comment]
lgtm

**Comment by alrapal** [comment]
Just for info, Dev should not be merged into feature branches. 
It does not impact since Dev was just based out of master, but if we had added the rasp pi code, this would have been problematic.

**Review by ktpa — COMMENTED** [review]
The playback of events is super slow, nothing I have noticed before (using the playback controls). Is this intended? 

Even when set to 5 it is still approximately 10 times slower than the real time event sender.

Apart from this the PR LGTM.

**Comment by kam56** [comment]
> 

Have you tested the playback of events on the master branch? They should be the same since I have not modified the event sender. If it's the same we can work on it on a separate branch. I don't think it is intended.

**Review by ktpa — APPROVED** [review]
Same aforementioned performance on upstream.

**Pull request merged**
