### PR TITLE
Us4 display node on hover

### LINKED ISSUE #4: Display time and link type on hover
#4 As a user I want to see information related to a chosen node in order to get a visual representation of what event I’m looking at.

**Acceptance Criteria**

- [x] Performance is not impacted
- [x] Popup is displayed on hover
- [x] Information displayed: - Link type   - Time (human readable)
- [x] Modify the data model to add link type
- [x] Comment code

### PR DESCRIPTION
**Pull request by alrapal**
# Display time and link type on hover

## Description:
* Modified lean-event to contain the link type 
* Use G6-graph's embedded edge labels to display link type 
* Use G6 graph's embedded node tooltips to display the time when the event was created. 
* We only change opacity to display or not display the labels since this is what impacts less the performance
  * On hover: 
    * Opacity of the link is increased (0.15 to 1)
    * Edge is made a bit thicker to better contrast
    * Opacity of the text is also increased (from 0 to 1) 
    * Label has shadow text to increase visibility (background colour is not usable in this case)
* We use the `groupByTypes: false` attribute in the graph option to allow controlling Z-index of the nodes. (So that labels would come on top of non hovered nodes). This is handled when a node is pushed into the graph to not impact performance. 
* Both outgoing and incoming edges are highlighted when hovering a node. 
 

## Useful links:
* [Z-index of elements in G6 graph
](https://antv-g6.gitee.io/en/docs/manual/middle/elements/methods/elementIndex)
* [Tooltips in G6 graph](https://g6.antv.vision/en/examples/tool/tooltip#tooltipPlugin )

### Overall App: 
Screenshot 2022-11-01 at 12 21 50

### When label on top of node
Screenshot 2022-11-01 at 12 22 42

### After solving conflicts 
Screenshot 2022-11-01 at 13 03 31

### Outgoing and incoming edges 

Screenshot 2022-11-03 at 13 04 01
Screenshot 2022-11-03 at 13 04 07

## Testing:
* Tested locally with event sender using DB dump data. User experience was not impacted by these changes: no slow downs have been noticed.  

## Possible Improvements:
* We can adjust `fontSize` and `fill` to make things even more visible. 
* An alternative to the label would be to activate the tooltip embedded into edges but possible problem regarding performances and also difficulties to trigger them when hovering another item than themselves. 

closes #4

### CODE REVIEW

**Review by gusaxtcha — APPROVED** [review]
Great job! I have left comments which includes a suggestion but that can be addressed in future features as it was not listed in the acceptance criteria of the issue created for this task.

**Comment by RuthgerD** [comment]
This looks quite nice indeed,
Just for my understanding, when you click on a node it will highlight all the nodes that reference it?

How is performance? I see quite some graph traversal in the frontend :^)

**Comment by alrapal** [comment]
> This looks quite nice indeed, Just for my understanding, when you click on a node it will highlight all the nodes that reference it?

Thanks! Kamila and I dived into G6 doc quite a lot to do this as efficient as possible. 
I don't think there is anything that has changed when clicking on a node, we only added interaction when hovering. 
At the moment, there is no highlight of nodes planned as part of the requirement, but it would be quite nice to look at it. I know there is a highlight mode that can be activated with the graph and if it does not impact performances too much, we can use that, otherwise we need to manipulate the style when hovering manually. 

I suspect the embedded "highlight relation" mode will impact quite a lot because it manipulates all nodes and edges (examples [here](https://g6.antv.vision/en/examples/interaction/highlight#activateRelations), which in a finite graph would not be a problem but might impact performances while the graph is growing. 

We need to further investigate :D (Either way, we would implement this as part of another PR) 

As for the current implementation when hovering, it just iterates through the edges connected to that node, put them on top and set label opacity to 1 for those nodes (as well as making edge a bit thicker and more visible to contrast with the rest)

> How is performance? I see quite some graph traversal in the frontend :^)

Locally, I could not see any impact on the performance, everything run smoothly while the event_sender was sending mocked data to the backend. 
I am not sure to understand what you mean with traversal? That edges are on top of nodes? =)

**Comment by RuthgerD** [comment]
Right, I meant the edges will show, what I was getting at is that it will highlight the edges that are caused by to hovered node

so say A caused B, then when you hover A the link between A and B light up, which means you go forward in time.

Another way could go is highlight the edges that caused the hovered node, which means you go back in time. I don't know if you have discussed this already, but it might be worth looking into supporting both ways.

Node highlight is not important, I think highlighting the edges is already very nice.
As for perf, try to get a hold of some real data; there are certain nodes that have more than 100 edges on them.

**Comment by alrapal** [comment]
> > We actually highlight both incoming edges and outgoing edges.
> 
> I think the screenshots just don't show it properly, but if you say it does both then great.

I added it in the PR description as well as a screenshot showing it goes both ways (could not find an example where both were shown at the same time with DB dump but you will have to believe us on this haha

**Pull request merged**
